Repository KouroshKSH/cs308-project, pull requests merged in 2025-04, with the labels that each got.

#52 Add cart page features (quantity control, size selection, and cart icon)
  frontend/src/Cart.js
Labels: enhancement

#60 Fix Backend Integration and Dynamic Product Fetching for Landing Page
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/productController.js
  backend/src/database/bulk_insert.js
  backend/src/database/create_db_run_schema.sql
  backend/src/database/departments_schema.sql
  backend/src/database/insert_bulk_departments.sql
  backend/src/database/insert_bulk_products.sql
  backend/src/database/products_schema.sql
  backend/src/models/product.js
  backend/src/products_cli.js
  backend/src/routes/index.js
  backend/src/routes/productRoutes.js
  backend/src/server.js
  frontend/src/LandingPage.js
Labels: bug, enhancement

#64 Sort by Popularity PR
  backend/src/controllers/productController.js
  backend/src/database/insert_bulk_products.sql
  backend/src/database/update_popularity_random.sql
  backend/src/models/product.js
  backend/src/routes/productRoutes.js
  frontend/src/LandingPage.js
Labels: enhancement

#66 Getting Product Review Endpoint and Database
  backend/src/controllers/productController.js
  backend/src/database/bulk_insert.js
  backend/src/database/create_db_run_schema.sql
  backend/src/database/insert_bulk_product_reviews.sql
  backend/src/database/insert_bulk_users.sql
  backend/src/database/product_reviews_schema.sql
  backend/src/insert_user.js
  backend/src/models/index.js
  backend/src/models/reviews.js
  backend/src/routes/productRoutes.js
Labels: enhancement

#70 Search endpoint
  backend/src/controllers/productController.js
  backend/src/database/insert_bulk_product_reviews.sql
  backend/src/database/insert_bulk_product_variations.sql
  backend/src/db_connection.js
  backend/src/models/product.js
  backend/src/products_cli.js
  backend/src/routes/index.js
  backend/src/routes/productRoutes.js
Labels: enhancement

#69 Left Drawer Fix with About and Contact Page
  frontend/src/App.js
  frontend/src/ContactPage.css
  frontend/src/ContactPage.js
  frontend/src/LandingPage.css
  frontend/src/LandingPage.js
  frontend/src/components/DrawerMenu.js
Labels: bug, enhancement

#83 Fix for Using Environmental Variables as URLs and Port Numbers
  backend/src/server.js
  frontend/src/LandingPage.js
Labels: enhancement

#84 Fix for Signup / User Registration
  backend/src/controllers/authController.js
  backend/src/models/user.js
  backend/src/server.js
  frontend/src/Signup.js
Labels: bug

#87 Fix for Cart Database and Backend Side
  backend/src/controllers/authController.js
  backend/src/controllers/cartController.js
  backend/src/database/carts_schema.sql
  backend/src/database/create_db_run_schema.sql
  backend/src/database/product_reviews_schema.sql
  backend/src/middleware/optionalAuthMiddleware.js
  backend/src/models/cart.js
  backend/src/routes/cartRoutes.js
  backend/src/server.js
Labels: bug, enhancement

#88 Updated the bulk insertion for users table
  backend/src/database/insert_bulk_users.sql
Labels: bug

#89 Updated the bulk insertion for product variations table
  backend/src/database/insert_bulk_product_variations.sql
Labels: enhancement

#91 Updated the Product Reviews Schema and Insertion
  backend/src/database/insert_bulk_product_reviews.sql
  backend/src/database/product_reviews_schema.sql
Labels: enhancement

#93 Cli for comment approval management
  backend/src/commentManagement_cli.js
  backend/src/models/reviews.js
Labels: enhancement

#96 Going from Landing Page to Product Page
  backend/src/controllers/productController.js
  backend/src/models/product.js
  backend/src/models/reviews.js
  backend/src/routes/productRoutes.js
  frontend/src/App.js
  frontend/src/LandingPage.js
  frontend/src/ProductPage.css
  frontend/src/ProductPage.js
  frontend/src/tempProductPage.css
  frontend/src/tempProductPage.js
Labels: bug

#109 Showing Product Images on Landing Page
  backend/src/models/product.js
  frontend/public/assets/images/placeholder.jpg
  frontend/public/assets/images/url_SN10.jpg
  frontend/public/assets/images/url_SN11.jpg
  frontend/public/assets/images/url_SN12.jpg
  frontend/public/assets/images/url_SN13.jpg
  frontend/public/assets/images/url_SN14.jpg
  frontend/public/assets/images/url_SN20.jpg
  frontend/public/assets/images/url_SN21.jpg
  frontend/public/assets/images/url_SN22.jpg
  frontend/public/assets/images/url_SN23.jpg
  frontend/public/assets/images/url_SN24.jpg
  frontend/public/assets/images/url_SN30.jpg
  frontend/public/assets/images/url_SN31.jpg
  frontend/public/assets/images/url_SN32.jpg
  frontend/public/assets/images/url_SN33.jpg
  frontend/public/assets/images/url_SN34.jpg
  frontend/src/LandingPage.css
  frontend/src/LandingPage.js
  frontend/src/ProductPage.js
  frontend/src/assets/images/product1.avif
  frontend/src/assets/images/product2.avif
  frontend/src/assets/images/product3.avif
  frontend/src/assets/images/product4.avif
  frontend/src/assets/images/product5.avif
  frontend/src/assets/images/product6.avif
  frontend/src/assets/images/product7.avif
  frontend/src/assets/images/product8.avif
  frontend/src/assets/images/product9.avif
Labels: enhancement

#101 Schemas and endpoints for orders, orderItems, returns and deliveries
  backend/src/controllers/deliveriesController.js
  backend/src/controllers/orderController.js
  backend/src/controllers/orderItemController.js
  backend/src/controllers/returnsController.js
  backend/src/database/create_db_run_schema.sql
  backend/src/database/deliveries_schema.sql
  backend/src/database/order_items_schema.sql
  backend/src/database/orders_schema.sql
  backend/src/database/returns_schema.sql
  backend/src/models/deliveries.js
  backend/src/models/order.js
  backend/src/models/orderItem.js
  backend/src/models/returns.js
  backend/src/routes/deliveriesRoutes.js
  backend/src/routes/index.js
  backend/src/routes/orderItemRoutes.js
  backend/src/routes/orderRoutes.js
  backend/src/routes/returnsRoutes.js
Labels: enhancement

#116 Removed the add to cart for each product on landing page
  frontend/src/LandingPage.js
Labels: bug

#118 Redesign of Cart DB and Endpoints
  backend/src/controllers/cartController.js
  backend/src/database/carts_schema.sql
  backend/src/models/cart.js
Labels: bug, enhancement

#120 Adding Product to Cart from Product Page (Frontend, Backend, DB)
  backend/src/controllers/authController.js
  backend/src/controllers/cartController.js
  backend/src/controllers/productController.js
  backend/src/models/cart.js
  backend/src/models/product.js
  backend/src/routes/cartRoutes.js
  backend/src/routes/productRoutes.js
  frontend/src/tempProductPage.js
  frontend/src/utils/sessionStorage.js
Labels: bug, enhancement

#121 Backend and DB Code for Posting a Product Review
  backend/src/controllers/productController.js
  backend/src/models/reviews.js
  backend/src/routes/productRoutes.js
Labels: enhancement

#126 Product page update and checkout page update
  frontend/src/App.js
  frontend/src/CheckoutPage.js
  frontend/src/LandingPage.js
  frontend/src/PaymentPage.js
  frontend/src/ProductPage.css
  frontend/src/ProductPage.js
  frontend/src/Signup.js
Labels: enhancement

#132 Major Fix for Backend and DB on Cart and Checkout Side
  backend/src/controllers/authController.js
  backend/src/controllers/orderController.js
  backend/src/models/cart.js
  frontend/src/Login.js
  frontend/src/utils/sessionStorage.js
Labels: bug

#123 Delivery management cli
  backend/src/controllers/orderController.js
  backend/src/database/deliveries_schema.sql
  backend/src/deliveryManagement_cli.js
  backend/src/models/cart.js
  backend/src/models/deliveries.js
  package-lock.json
Labels: bug, enhancement

#134 Added star ratings based on popularity score
  frontend/src/LandingPage.css
  frontend/src/LandingPage.js
Labels: enhancement

#137 fixed issue with all products having 4 stars
  frontend/src/ProductPage.js
Labels: bug

#138 Fixes for Product Page Navigation and UI
  frontend/src/Header.js
  frontend/src/LandingPage.js
  frontend/src/ProductPage.js
Labels: bug

#140 Fix for Product Page's Add to Cart Weird Behavior
  frontend/src/ProductPage.js
Labels: bug

#143 made session ID expire every 5 min
  frontend/src/utils/sessionStorage.js
Labels: enhancement

#146 PR for Mini Cart
  frontend/src/Header.js
  frontend/src/LandingPage.js
  frontend/src/components/MiniCart.js
  frontend/src/utils/sessionStorage.js
Labels: bug, enhancement

#150 Feature for Cart to Checkout to Invoice and Full Demo Test Success
  backend/src/controllers/authController.js
  frontend/src/App.js
  frontend/src/CheckoutPage.js
  frontend/src/InvoicePage.js
  frontend/src/Login.js
  frontend/src/Signup.js
  frontend/src/components/MiniCart.js
Labels: enhancement

#152 invoice pdf works now thanks to Zeynep
  frontend/package-lock.json
  frontend/package.json
  frontend/src/InvoicePage.js
Labels: enhancement

#153 Fixed Search in Header and Backend for Better Results
  frontend/src/Header.js
  frontend/src/LandingPage.js
Labels: bug

#154 Some Styling Touches for UI
  frontend/src/Header.js
  frontend/src/ProfilePage.js
Labels: enhancement
