Repository KouroshKSH/cs308-project, pull requests merged in 2025-03, with the labels that each got.

#4 Project Setup
  backend/.env
  backend/src/config/db.js
  backend/src/controllers/index.js
  backend/src/models/index.js
  backend/src/routes/index.js
  backend/src/server.js
  frontend/.env
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/index.js
  frontend/src/context/index.js
  frontend/src/hooks/index.js
  frontend/src/pages/Dashboard.js
  frontend/src/pages/Home.js
  frontend/src/pages/Login.js
Labels: enhancement

#7 Did the server setup
  backend/src/server.js
Labels: enhancement

#9 Did the setup for the frontend
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/index.js
  frontend/src/context/index.js
  frontend/src/hooks/index.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/pages/Dashboard.js
  frontend/src/pages/Home.js
  frontend/src/pages/Login.js
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: enhancement

#13 Wrote script to automate backend and frontend
  script.sh
Labels: enhancement

#15 Feature/productdb
  backend/src/database/insert_products.sql
  backend/src/database/schema.sql
Labels: bug

#16 AAdded Sign-Up Page & Linked to Login
  frontend/src/App.js
  frontend/src/Login.test.js
  frontend/src/signUp.js
Labels: enhancement

#21 Connecting Frontend to Backend for User Authentication
  README.md
  backend/src/controllers/authController.js
  backend/src/insert_user.js
  backend/src/models/user.js
  backend/src/routes/index.js
  backend/src/server.js
  frontend/src/Login.js
  frontend/src/Signup.js
  instructions.md
  script.sh
Labels: enhancement

#31 Fix/prconflicts
  README.md
  backend/src/controllers/authController.js
  backend/src/database/testing_login.txt
  backend/src/insert_user.js
  backend/src/models/user.js
  backend/src/routes/index.js
  backend/src/server.js
  frontend/src/App.js
  frontend/src/Login.js
  frontend/src/Signup.js
  instructions.md
  script.sh
Labels: bug

#26 Final fix branch 1
  frontend/src/App.js
  frontend/src/LandingPage.css
  frontend/src/LandingPage.js
  frontend/src/Login.js
  frontend/src/Signup.js
Labels: enhancement

#36 Fixed Dashboard Route by Auth Bypass
  frontend/src/App.js
  frontend/src/Login.js
  frontend/src/ProtectedRoute.js
  package-lock.json
  package.json
Labels: bug

#37 changed all turkish words to english
  frontend/src/LandingPage.js
Labels: bug

#38 added back to home button for user auth screens
  frontend/src/Login.js
  frontend/src/Signup.js
Labels: enhancement

#40 Made Initial Product List on Landing Page
  frontend/src/LandingPage.css
  frontend/src/LandingPage.js
  frontend/src/assets/images/product1.avif
  frontend/src/assets/images/product2.avif
  frontend/src/assets/images/product3.avif
  frontend/src/assets/images/product4.avif
  frontend/src/assets/images/product5.avif
  frontend/src/assets/images/product6.avif
  frontend/src/assets/images/product7.avif
  frontend/src/assets/images/product8.avif
  frontend/src/assets/images/product9.avif
Labels: enhancement

#47 New Features: Cart, Checkout and Profile Page
  backend/src/database/testing_login.txt
  frontend/src/App.js
  frontend/src/CheckoutPage.js
  frontend/src/LandingPage.js
  frontend/src/Login.js
  frontend/src/ProfilePage.js
  frontend/src/Signup.js
Labels: bug, enhancement
