Repository KouroshKSH/cs308-project, pull requests merged in 2025-05, with the labels that each got.

#158 PR for Cart Table's Schema Update about Unique Keys
  backend/src/database/carts_schema.sql
Labels: bug

#160 PR for Mini Cart Visual Improvements
  backend/src/models/cart.js
  frontend/src/components/MiniCart.js
Labels: enhancement

#165 Updated Profile Page with Cart Items and UI Updates
  backend/src/models/cart.js
  frontend/src/ProfilePage.js
Labels: enhancement

#168 Endpoints for reviews + getdeliveriesbystatus
  backend/src/controllers/deliveriesController.js
  backend/src/controllers/reviewsController.js
  backend/src/insert_user.js
  backend/src/models/deliveries.js
  backend/src/routes/deliveriesRoutes.js
  backend/src/routes/index.js
  backend/src/routes/reviewsRoutes.js
Labels: enhancement

#181 Fix for Database Products and their Category IDs
  backend/src/database/fix_for_product_category_id.sql
  backend/src/database/insert_bulk_products.sql
Labels: bug

#170 Add filtering products by department and category
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/productController.js
  backend/src/models/index.js
  backend/src/models/product.js
  backend/src/routes/productRoutes.js
  backend/src/server.js
Labels: enhancement

#184 Filtering by Category Frontend
  frontend/src/pages/LandingPage.css
  frontend/src/pages/LandingPage.js
Labels: enhancement

#186 Manager Authentication Page - Fullstack
  backend/src/controllers/authController.js
  backend/src/database/testing_login.txt
  backend/src/insert_user.js
  backend/src/routes/authRoutes.js
  frontend/src/App.js
  frontend/src/components/DrawerMenu.js
  frontend/src/components/ProtectedRoute.js
  frontend/src/pages/ManagerLogin.js
  frontend/src/pages/ProductManagerPage.js
  frontend/src/pages/ProfilePage.js
  frontend/src/pages/SalesManagerPage.js
Labels: enhancement

#175 Reviews update: updating error messages and updating posted reviews (Issue #169)
  frontend/src/pages/ProductPage.js
Labels: bug

#188 Fix for the Checkout Forgetting User Auth - Bug 187
  frontend/src/App.js
  frontend/src/components/MiniCart.js
  frontend/src/components/ProtectedRoute.js
Labels: bug

#191 Product Manager and the Deliveries Fullstack
  backend/src/controllers/orderController.js
  backend/src/models/deliveries.js
  frontend/src/pages/ProductManagerPage.css
  frontend/src/pages/ProductManagerPage.js
Labels: bug, enhancement

#199 Minor UI changes for sales manager page
  frontend/src/pages/SalesManagerPage.js
Labels: enhancement

#204 Footer for Almost All Necessary Pages
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/Footer.css
  frontend/src/components/Footer.js
  frontend/src/pages/ContactPage.css
  frontend/src/pages/ContactPage.js
  frontend/src/pages/LandingPage.css
  frontend/src/pages/LandingPage.js
  frontend/src/pages/OrderStatusPage.css
  frontend/src/pages/OrderStatusPage.js
  frontend/src/pages/ProductManagerPage.js
  frontend/src/pages/ProductPage.css
  frontend/src/pages/ProductPage.js
  frontend/src/pages/ProfilePage.js
  frontend/src/pages/SalesManagerPage.js
Labels: enhancement

#206 Updated Contact Page
  frontend/public/assets/images/contact-us.png
  frontend/src/pages/ContactPage.css
  frontend/src/pages/ContactPage.js
Labels: enhancement

#208 Frontend for Comment Moderation by Product Manager
  frontend/src/pages/ProductManagerPage.js
Labels: enhancement

#212 Temporary About Us Page
  frontend/src/App.js
  frontend/src/components/DrawerMenu.js
  frontend/src/components/Footer.js
  frontend/src/pages/AboutPage.js
Labels: enhancement

#216 Frontend for Wishlist
  backend/src/models/wishlist.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/pages/LandingPage.css
  frontend/src/pages/LandingPage.js
  frontend/src/pages/ProductPage.css
  frontend/src/pages/ProductPage.js
  frontend/src/pages/ProfilePage.js
Labels: enhancement

#219 Sales Campaign Fullstack - 218
  backend/src/controllers/productController.js
  backend/src/controllers/salesCampaignController.js
  backend/src/database/create_db_run_schema.sql
  backend/src/database/sales_campaigns_schema.sql
  backend/src/models/product.js
  backend/src/models/salesCampaign.js
  backend/src/routes/index.js
  backend/src/routes/productRoutes.js
  backend/src/routes/salesCampaignRoutes.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/AboutPage.js
  frontend/src/pages/LandingPage.css
  frontend/src/pages/LandingPage.js
  frontend/src/pages/ProductManagerPage.css
  frontend/src/pages/ProductManagerPage.js
  frontend/src/pages/ProductPage.css
  frontend/src/pages/ProductPage.js
  frontend/src/pages/SalesManagerPage.css
  frontend/src/pages/SalesManagerPage.js
Labels: enhancement

#205 [BUG] Fix hydration error (#197)
  frontend/src/pages/ManagerLogin.js
Labels: bug

#224 Fixes for Sales Campaigns about Cart, Wishlist, Checkout, Sort, Search and Filter
  backend/src/controllers/orderController.js
  backend/src/models/cart.js
  backend/src/models/product.js
  backend/src/models/wishlist.js
  frontend/src/components/MiniCart.css
  frontend/src/components/MiniCart.js
  frontend/src/pages/CheckoutPage.css
  frontend/src/pages/CheckoutPage.js
  frontend/src/pages/ProfilePage.css
  frontend/src/pages/ProfilePage.js
Labels: bug

#227 Product Manager and Customer Pages Updates
  backend/src/controllers/orderController.js
  backend/src/models/reviews.js
  backend/src/routes/orderRoutes.js
  frontend/src/pages/ProductManagerPage.css
  frontend/src/pages/ProductManagerPage.js
  frontend/src/pages/ProfilePage.js
Labels: bug, enhancement

#234 Sales Manager Handling Returns (frontend, backend, database)
  backend/src/controllers/returnsController.js
  backend/src/database/returns_schema.sql
  backend/src/models/productVariations.js
  backend/src/models/returns.js
  frontend/src/pages/OrderStatusPage.js
  frontend/src/pages/ProductPage.js
  frontend/src/pages/SalesManagerPage.js
Labels: enhancement

#232 Endpoints for: adding, deleting products + setting price
  backend/src/controllers/orderController.js
  backend/src/controllers/productController.js
  backend/src/models/order.js
  backend/src/models/product.js
  backend/src/routes/orderRoutes.js
  backend/src/routes/productRoutes.js
Labels: enhancement

#235 Bulk Insert for Sales Campaigns - 231
  backend/src/database/bulk_insert.js
  backend/src/database/insert_bulk_sales_campaigns.sql
Labels: enhancement

#238 General UI Updates
  frontend/public/assets/images/noire-vogue-logo.png
  frontend/src/components/DrawerMenu.js
  frontend/src/components/Footer.css
  frontend/src/components/Footer.js
  frontend/src/pages/LandingPage.css
  frontend/src/pages/LandingPage.js
Labels: enhancement

#248 Product Manager Category Management, Fixes for Deliveries and Comments, Separation of Product from Category Management
  backend/src/controllers/categoryController.js
  backend/src/models/category.js
  backend/src/routes/categoryRoutes.js
  backend/src/routes/index.js
  frontend/src/pages/ProductManagerPage.css
  frontend/src/pages/ProductManagerPage.js
Labels: bug, enhancement

#246 Redesign About page: centered logo, clean layout, no visual clutter
  frontend/src/pages/AboutPage.js
Labels: enhancement

#251 Sales Manager and Charts
  frontend/src/pages/SalesManagerPage.css
  frontend/src/pages/SalesManagerPage.js
Labels: enhancement

#254 Frontend for Invoice Management for Sales Manager
  frontend/src/pages/SalesManagerPage.js
Labels: enhancement

#256 Price Managmenet for Sales Manager
  backend/src/controllers/orderController.js
  backend/src/models/order.js
  backend/src/models/product.js
  frontend/src/pages/LandingPage.js
  frontend/src/pages/ProductPage.js
  frontend/src/pages/SalesManagerPage.js
Labels: enhancement
